version: '3.9'
services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - final-project:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432' # Expose if needed

  web:
    build: .
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./src:/home/node/app
      - /home/node/app/node_modules
    env_file: .env

volumes:
  final-project:
